name: Deploy de uma aplicação Spring Boot usando o OpenTofu + AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t brunos4ntos/opentofu .

      - name: Publish image to docker hub
        run: docker push brunos4ntos/opentofu:latest

      - name: Install OpenTofu
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method standalone
          rm install-opentofu.sh

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Apply
        id: opentofu-apply
        run: |
          tofu apply -auto-approve
          echo "INSTANCE_IP=$(tofu output -raw instance_ip)" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Debug instance IP
        run:
          echo "$INSTANCE_IP"

      - name: Install Docker and Run Container on EC2
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > chave-ssh-opentofu.pem
          chmod 400 chave-ssh-opentofu.pem
          ssh -o StrictHostKeyChecking=no -i chave-ssh-opentofu.pem ec2-user@${{ env.INSTANCE_IP }} << EOF
            sudo yum update -y
            sudo amazon-linux-extras install docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user
            docker pull brunos4ntos/opentofu:latest
            docker run -d -p 8080:8080 brunos4ntos/opentofu:latest
          EOF
          rm chave-ssh-opentofu.pem
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
